services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres-db-initializer"
    container_name: "initializer"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/data/db"
    volumes:
       - db:/data/db
       - ${DUMP_FILE_LOCATION}/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    restart: unless-stopped
volumes:
    db:
      name: ${POSTGRES_DB}
      driver: local
      driver_opts:
       o: bind
       type: none
       device: ${LOCAL_DEVICE_PGDATA}
